/**
 * Supabase database types — auto-generated from your schema.
 *
 * To regenerate after schema changes:
 *   npm run db:types
 *
 * Or manually:
 *   npx supabase gen types typescript --project-id=$SUPABASE_PROJECT_ID > src/types/database.ts
 *
 * DO NOT edit this file manually — it will be overwritten by the generator.
 */

// Placeholder — replace with generated types after connecting Supabase
export type Database = {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
};
